#ifndef _MBEDTLS_CONFIG_H
#define _MBEDTLS_CONFIG_H

#define MBEDTLS_SHA256_C
#if LIB_PICO_SHA256
// Enable hardware acceleration
//#define MBEDTLS_SHA256_ALT
#endif
#define MBEDTLS_SHA384_C

#define MBEDTLS_PSA_CRYPTO_C 
#define MBEDTLS_PSA_CRYPTO_CONFIG

#define MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_ENTROPY_HARDWARE_ALT
#define MBEDTLS_ENTROPY_C
#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_AES_C

#define MBEDTLS_ECDSA_C
#define MBEDTLS_ECP_C
#define MBEDTLS_BIGNUM_C
#define MBEDTLS_ECP_DP_SECP384R1_ENABLED
#define MBEDTLS_ECP_DP_SECP256R1_ENABLED

#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_ASN1_WRITE_C

#endif